name: CI
on: [workflow_dispatch]
jobs:
  codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pushes to codecommit
        env:
          USERNAME: ${{ secrets.AWS_USERNAME }}
          PASSWORD: ${{ secrets.AWS_PASSWORD }}
        shell: bash
        run: |
          git clone ssh://$USERNAME:$PASSWORD@git-codecommit.ap-south-1.amazonaws.com/v1/repos/testing
