name: CI
on: [workflow_dispatch]
jobs:
  codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: checkout from codecommit
#         env:
#           USERNAME: ${{ secrets.AWS_USERNAME }}
#           PASSWORD: ${{ secrets.AWS_PASSWORD }}
        shell: bash
        run: |
          git clone "https://${{ vars.AWS_USERNAME }}:${{ vars.AWS_PASSWORD }}@git-codecommit.ap-south-1.amazonaws.com/v1/repos/testing" 
#         with:
#           path: main
#           ref: main
